### ISSUE TITLE
Continuous Integration setup

### ISSUE THREAD

**Issue by matteodv99tn** [idra-lab/unitree_z1_hw_interface#4]
Hy @Hydran00 , I know that you already did some CI setup... can you help me setup the continuous integration for this project?
We could target mainly ROS2 humble, but also foxy and jazzy could be a nice to have.

For now we can just make sure that the workspace compile, and in the future we might add testing for the formatting and static linting of the code.
CI shall target the `main` and `devel` branches, as well as pull requests on `devel`.

Let me know if you can help me!

**Comment by Hydran00** [comment]
I will try to do it today with something like [this](https://github.com/lucabeber/effort_controller/blob/main/.github/workflows/humble.yml).
For submodules I think it is sufficient to use github `actions/checkout@v3` like this:
```
- uses: actions/checkout@v3
  with:
    submodules: recursive
```

**Comment by matteodv99tn** [comment]
Thanks for the help. Try to use that CI configuration with the update you posted, and hopefully it works.

Anyway, I'm working on a [new branch](https://github.com/idra-lab/z1_ros2/tree/hardware-interface-rewrite) where I am removing the dependency from gitmodules, so hopefully this will not be a problem moving onward

**Comment by Hydran00** [comment]
The CI is failing with this errors when installing dependencies with rosdep:
```
  ERROR: the following packages/stacks could not have their rosdep keys resolved
  to system dependencies
  z1_hw_interface: Cannot locate rosdep definition for [rclcpp_lifecyle]
  z1_bringup: Cannot locate rosdep definition for [z1_hardware_interface]
```
I will investigate the problem. I think that the `z1_hardware_interface` dependency in `z1_bringup` should be renamed `z1_hw_interface` and `rclcpp_lifecyle` is not a ros2 package.

Edit:
In the `ros2_control_demos` repo they use 
```
...
<depend>rclcpp_lifecycle</depend>
...
```
as well. I don't know why it fails with rosdep.

**Comment by matteodv99tn** [comment]
About the dependency on `z1_hardware_interface`, I most probably messed up versioning, since I moved `z1_hw_interface` to `z1_hardware_interface`, so that is a reasonable error.

Concerning the `rclcpp_lifecycle` dependency, I quickly search on the internet. As reported [here](https://index.ros.org/p/rclcpp_lifecycle/), it shall be part of the ROS2 core `rclcpp` library, so it must come with that.

Thanks for your work, this afternoon I will fix everything.
