### ISSUE TITLE
github CI fails due to CMake error

### ISSUE THREAD

**Issue by Hydran00** [idra-lab/unitree_z1_hw_interface#5]
It seems that there is an error due to modules in the CMake.
https://github.com/idra-lab/z1_ros2/actions/runs/12545689409/job/34980302277

**Comment by matteodv99tn** [comment]
Had to do some hard pushes to fix some subtle bugs, but now everything shall be fixed, and the CI is working as expected.
The package now builds correctly both in humble, jazzy, and rolling!
